### ISSUE TITLE
`NoMethodError (undefined method 'parent_ids_for' for #<User:0x0000000114d6def8>)`

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-roles#5]
```
2.7.2 :006 > Ability.new(User.last).can? :create, Scaffolding::AbsolutelyAbstract::CreativeConcept
  User Load (0.6ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
  Membership Load (0.2ms)  SELECT "memberships".* FROM "memberships" WHERE "memberships"."user_id" = $1  [["user_id", 1]]
Traceback (most recent call last):
       16: from railties (6.1.3.2) lib/rails/commands/console/console_command.rb:102:in `perform'
       15: from railties (6.1.3.2) lib/rails/commands/console/console_command.rb:19:in `start'
       14: from railties (6.1.3.2) lib/rails/commands/console/console_command.rb:70:in `start'
       13: from (irb):6
       12: from (irb):6:in `new'
       11: from app/models/ability.rb:41:in `initialize'
       10: from bullet_train-roles (f5992fb490db) lib/roles/permit.rb:15:in `permit'
        9: from bullet_train-roles (f5992fb490db) lib/roles/permit.rb:15:in `each'
        8: from bullet_train-roles (f5992fb490db) lib/roles/permit.rb:19:in `block in permit'
        7: from bullet_train-roles (f5992fb490db) lib/roles/permit.rb:44:in `add_abilities_for'
        6: from bullet_train-roles (f5992fb490db) lib/models/role.rb:99:in `ability_generator'
        5: from bullet_train-roles (f5992fb490db) lib/models/role.rb:99:in `each'
        4: from bullet_train-roles (f5992fb490db) lib/models/role.rb:100:in `block in ability_generator'
        3: from bullet_train-roles (f5992fb490db) lib/models/role.rb:100:in `new'
        2: from bullet_train-roles (f5992fb490db) lib/models/role.rb:147:in `initialize'
        1: from activemodel (6.1.3.2) lib/active_model/attribute_methods.rb:469:in `method_missing'
NoMethodError (undefined method `parent_ids_for' for #<User:0x0000000114d6def8>)
```

**Comment by andrewculver** [comment]
`Role` depends on `User` having a `parent_ids_for` defined, but the Ruby Gem doesn't provide any default implementation for it. We should extract that into a concern and include it in the Ruby Gem. However, when we extract it, we should remove any references to the ability cache, as that's a Bullet Train specific feature.

We'll also want to make the installer add this concern to `User` automatically.

**Comment by andrewculver** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train-roles/commit/6f0214554db30b85eb843815bac70f13e0d7c310 .
